# # ─── CONFIGURAÇÃO DO MICROSOFT SQL SERVER SENAC──────────────────────
# spring.datasource.url=jdbc:sqlserver://localhost:65346;databaseName=central_imoveis;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
# spring.datasource.hikari.auto-commit=true

# # Driver e Dialeto para o Hibernate se adaptar ao padrão Microsoft
# spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# # ddl-auto como update para criar as tabelas e NUNCA mais apagar os dados
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# jwt.secret=9a4f2c8d3e1b7a6f5c4d3b2a1e0f9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a


# ─── CONFIGURAÇÃO DO MICROSOFT SQL SERVER CASA ──────────────────────
spring.datasource.url=jdbc:sqlserver://localhost:60927;databaseName=central_imoveis;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.hikari.auto-commit=true

# Driver e Dialeto para o Hibernate se adaptar ao padrão Microsoft
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ddl-auto como update para criar as tabelas e NUNCA mais apagar os dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=9a4f2c8d3e1b7a6f5c4d3b2a1e0f9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a


# ─── CONFIGURAÇÃO PARA CADASTRO DE IMAGEM EM IMÓVEL ──────────────────────
# Aumenta o limite máximo de tamanho de um arquivo individual
spring.servlet.multipart.max-file-size=10MB

# Aumenta o limite máximo da requisição inteira (form + imagem)
spring.servlet.multipart.max-request-size=10MB