# URL de conexão: altera para o nome do seu banco de dados local (ex: central_imoveis)
spring.datasource.url=jdbc:postgresql://localhost:8080/central_imoveis
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_DO_POSTGRES

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Estratégia de criação das tabelas (Dica: use 'update' para desenvolvimento)
spring.jpa.hibernate.ddl-auto=update